=== daniel-giralt-len/5ein.es/test/schema/class/class.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"version": "2.6.2",
	"$id": "class.json",

	"type": "object",

	"definitions": {
		"classTableGroup": {
			"type": "object",
			"properties": {
				"title": {
					"type": "string"
				},
				"subclasses": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"source": {
								"type": "string"
							}
						},
						"required": ["name", "source"],
						"additionalProperties": false
					}
				},
				"colLabels": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"rows": {
					"type": "array",
					"items": {
						"type": "array",
						"items": {
							"$ref": "entry.json"
						}
					}
				}
			},
			"required": [
				"colLabels",
				"rows"
			],
			"additionalProperties": false
		},

		"classFeature": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"source": {"type": "string"},
				"srd": {"type": "boolean"},
				"className":  {"type": "string"},
				"classSource": {"type": "string"},
				"level":  {"type": "integer"},
				"header":  {"type": "integer"},
				"page": {"type": "integer"},
				"type": {"type": "string", "enum": ["inset"]},
				"entries": {
					"type": "array",
					"items": {
						"$ref": "entry.json"
					}
				},
				"isClassFeatureVariant": {"type": "boolean"},
				"otherSources": {
					"$ref": "util.json#/definitions/otherSources"
				}
			},
			"required": [
				"name",
				"source",
				"className",
				"classSource",
				"level",
				"entries"
			],
			"additionalProperties": false
		},
		"subclassFeature": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"source": {"type": "string"},
				"srd": {"type": "boolean"},
				"className":  {"type": "string"},
				"classSource": {"type": "string"},
				"subclassShortName":  {"type": "string"},
				"subclassSource": {"type": "string"},
				"level":  {"type": "integer"},
				"header":  {"type": "integer"},
				"page": {"type": "integer"},
				"type": {"type": "string", "enum": ["inset"]},
				"entries": {
					"type": "array",
					"items": {
						"$ref": "entry.json"
					}
				},
				"isClassFeatureVariant": {"type": "boolean"},
				"isGainAtNextFeatureLevel": {
					"description": "If this feature should only be (optionally) gained at the next \"gainSubclassFeature\" level, rather than at the level listed on the feature.",
					"type": "boolean"
				},
				"otherSources": {
					"$ref": "util.json#/definitions/otherSources"
				}
			},
			"required": [
				"name",
				"source",
				"className",
				"classSource",
				"subclassShortName",
				"subclassSource",
				"level",
				"entries"
			],
			"additionalProperties": false
		},

		"proficiencies": {
			"type": "object",
			"properties": {
				"armor": {
					"type": "array",
					"items": {
						"oneOf": [
							{
								"type": "string",
								"enum": [
									"light", "medium", "heavy", "{@item shield|phb|shields}"
								]
							},
							{
								"type": "object",
								"properties": {
									"proficiency": {
										"type": "string",
										"enum": [
											"light", "medium", "heavy", "{@item shield|phb|shields}", "special"
										]
									},
									"full": {
										"description": "The complete text for this proficiency.",
										"type": "string"
									}
								},
								"required": ["proficiency", "full"]
							}
						]
					}
				},
				"weapons": {
					"type": "array",
					"items": {
						"oneOf": [
							{
								"type": "string"
							},
							{
								"type": "object",
								"properties": {
									"proficiency": {"type": "string"},
									"optional": {"type": "boolean"}
								},
								"additionalProperties": false,
								"required": ["proficiency", "optional"]
							}
						]
					}
				},
				"tools": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"skills": {
					"$ref": "util.json#/definitions/skillProficiencies"
				}
			}
		},

		"subclass": {
			"anyOf": [
				{
					"type": "object",
					"$$merge": [
						{
							"$ref": "#/definitions/subclassData"
						},
						{
							"required": [
								"name",
								"shortName",
								"source",
								"className",
								"classSource",
								"subclassFeatures"
							]
						}
					]
				},
				{
					"type": "object",
					"$$merge": [
						{
							"$ref": "#/definitions/subclassData"
						},
						{
							"$ref": "util.json#/definitions/copyBlock"
						}
					]
				}
			]
		},

		"subclassData": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"shortName": {
					"type": "string"
				},
				"source": {
					"type": "string"
				},
				"className": {
					"description": "The name of the class this subclass belongs to. Homebrew use only",
					"type": "string"
				},
				"classSource": {
					"description": "The source of the class this subclass belongs to (defaults to PHB). Homebrew use only",
					"type": "string"
				},
				"isReprinted": {
					"type": "boolean"
				},
				"srd": {
					"type": "boolean"
				},
				"page": {
					"type": "integer"
				},
				"casterProgression": {
					"enum": ["full", "1/2", "1/3", "pact", "artificer"]
				},
				"spellcastingAbility": {
					"enum": ["str", "dex", "con", "int", "wis", "cha"]
				},
				"cantripProgression": {
					"type": "array",
					"items": {
						"type": "integer"
					},
					"minItems": 20,
					"maxItems": 20
				},
				"spellsKnownProgression": {
					"type": "array",
					"items": {
						"type": "integer"
					},
					"minItems": 20,
					"maxItems": 20
				},
				"subclassFeatures": {
					"type": "array",
					"items": {
						"oneOf": [
							{
								"type": "string"
							},
							{
								"type": "object",
								"properties": {
									"subclassFeature": {
										"type": "string"
									},
									"gainSubclassFeature": {
										"type": "boolean"
									}
								},
								"required": ["subclassFeature"]
							}
						]
					}
				},
				"subclassTableGroups": {
					"type": "array",
					"items": { "$ref": "#/definitions/classTableGroup"}
				},
				"otherSources": {
					"$ref": "util.json#/definitions/otherSources"
				},
				"additionalSpells": { "$ref": "util.json#/definitions/additionalSpellsArray" },
				"subclassSpells": {
					"description": "Homebrew use only",
					"type": "array",
					"items": {"$ref": "#/definitions/spellRef"}
				},
				"subSubclassSpells": {
					"description": "Homebrew use only",
					"type": "array",
					"items": {"$ref": "#/definitions/spellRef"}
				}
			},
			"additionalProperties": false
		},

		"requirements": {
			"type": "object",
			"properties": {
				"str": {
					"type": "integer"
				},
				"dex": {
					"type": "integer"
				},
				"con": {
					"type": "integer"
				},
				"int": {
					"type": "integer"
				},
				"wis": {
					"type": "integer"
				},
				"cha": {
					"type": "integer"
				},
				"or": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"str": {
								"type": "integer"
							},
							"dex": {
								"type": "integer"
							},
							"con": {
								"type": "integer"
							},
							"int": {
								"type": "integer"
							},
							"wis": {
								"type": "integer"
							},
							"cha": {
								"type": "integer"
							}
						},
						"additionalProperties": false
					}
				},
				"entries": {
					"type": "array",
					"items": {
						"$ref": "entry.json"
					}
				}
			},
			"additionalProperties": false
		},

		"class": {
			"anyOf": [
				{
					"type": "object",
					"$$merge": [
						{
							"$ref": "#/definitions/classData"
						},
						{
							"required": [
								"name",
								"source",
								"classFeatures"
							]
						}
					]
				},
				{
					"type": "object",
					"$$merge": [
						{
							"$ref": "#/definitions/classData"
						},
						{
							"$ref": "util.json#/definitions/copyBlock"
						}
					]
				}
			]
		},

		"classData": {
			"description" : "A character class",

			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"source": {
					"type": "string"
				},
				"otherSources": {
					"$ref": "util.json#/definitions/otherSources"
				},
				"srd": {
					"type": "boolean"
				},
				"isReprinted": {
					"type": "boolean"
				},
				"isSidekick": {
					"type": "boolean"
				},
				"hd": {
					"type": "object",
					"properties": {
						"number": {
							"type": "integer"
						},
						"faces": {
							"type": "integer"
						}
					},
					"required": [
						"number",
						"faces"
					],
					"additionalProperties": false
				},
				"proficiency": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": ["str", "dex", "con", "int", "wis", "cha"]
					}
				},
				"classTableGroups": {
					"type": "array",
					"items": { "$ref": "#/definitions/classTableGroup"}
				},
				"startingProficiencies": {
					"$ref": "#/definitions/proficiencies"
				},
				"startingEquipment": {
					"type": "object",
					"properties": {
						"additionalFromBackground": {
							"type": "boolean"
						},
						"default": {
							"type": "array",
							"items": {
								"type": "string"
							}
						},
						"defaultData": {
							"$ref": "util.json#/definitions/startingEquipment"
						},
						"goldAlternative": {
							"type": "string"
						}
					},
					"required": [
						"additionalFromBackground",
						"default"
					],
					"additionalProperties": false
				},
				"requirements": {"$ref": "#/definitions/requirements"},
				"multiclassing": {
					"type": "object",
					"properties": {
						"requirements": {"$ref": "#/definitions/requirements"},
						"proficienciesGained": {
							"$ref": "#/definitions/proficiencies"
						},
						"entries": {
							"type": "array",
							"items": {"$ref": "entry.json"}
						}
					},
					"additionalProperties": false
				},
				"casterProgression": {
					"enum": ["full", "1/2", "1/3", "pact", "artificer"]
				},
				"preparedSpells": {
					"type": "string"
				},
				"spellcastingAbility": {
					"enum": ["str", "dex", "con", "int", "wis", "cha"]
				},
				"cantripProgression": {
					"type": "array",
					"items": {
						"type": "integer"
					},
					"minItems": 20,
					"maxItems": 20
				},
				"spellsKnownProgression": {
					"type": "array",
					"items": {
						"type": "integer"
					},
					"minItems": 20,
					"maxItems": 20
				},
				"spellsKnownProgressionFixed": {
					"description": "For e.g. Wizard, where the spells taken at each level must be <= the max spellcasting level, and cannot be swapped out afterward.",
					"type": "array",
					"items": {
						"type": "integer"
					},
					"minItems": 20,
					"maxItems": 20
				},
				"spellsKnownProgressionFixedAllowLowerLevel": {"type": "boolean"},
				"spellsKnownProgressionFixedByLevel": {
					"description": "For e.g. Warlock Mystic Arcanum. A map of <class level> -> <spell level> -> <number of spells known>",
					"type": "object",
					"patternProperties": {
						"^\\d+$": {
							"type": "object",
							"properties": {
								"1": {"type": "integer"},
								"2": {"type": "integer"},
								"3": {"type": "integer"},
								"4": {"type": "integer"},
								"5": {"type": "integer"},
								"6": {"type": "integer"},
								"7": {"type": "integer"},
								"8": {"type": "integer"},
								"9": {"type": "integer"}
							},
							"additionalProperties": false
						}
					},
					"additionalProperties": false
				},
				"optionalfeatureProgression": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {"type": "string"},
							"featureType": {"$ref": "util.json#/definitions/dataOptionalfeatureType"},
							"progression": {
								"type": "array",
								"items": {"type": "integer"},
								"minItems": 20,
								"maxItems": 20
							}
						},
						"required": ["name", "featureType", "progression"]
					}
				},
				"classFeatures": {
					"type": "array",
					"items": {
						"oneOf": [
							{
								"type": "string"
							},
							{
								"type": "object",
								"properties": {
									"classFeature": {
										"type": "string"
									},
									"gainSubclassFeature": {
										"type": "boolean"
									}
								},
								"required": ["classFeature"]
							}
						]
					}
				},
				"subclassTitle": {
					"type": "string"
				},
				"page": {
					"type": "integer"
				},
				"fluff": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"entries": {
								"type": "array",
								"items": {"$ref": "entry.json"}
							},
							"page": {
								"type": "integer"
							},
							"source": {
								"type": "string"
							},
							"type": {
								"type": "string"
							}
						},
						"required": ["entries", "source"],
						"additionalProperties": false
					}
				},
				"additionalSpells": { "$ref": "util.json#/definitions/additionalSpellsArray" },
				"classSpells": {
					"description": "Homebrew use only",
					"type": "array",
					"items": {"$ref": "#/definitions/spellRef"}
				}
			},
			"additionalProperties": false
		},

		"spellRef": {
			"description": "A reference to a spell, linked by name and source. Assumes PHB as the source, if none is provided.",
			"oneOf": [
				{
					"description": "A spell with a non-PHB source",
					"type": "object",
					"properties": {
						"name": {
							"type": "string"
						},
						"source": {
							"type": "string"
						}
					},
					"required": [
						"name", "source"
					],
					"additionalProperties": false
				},
				{
					"description": "Another class/subclass/subsubclass's spell list",
					"type": "object",
					"properties": {
						"className": {"type": "string"},
						"classSource": {"type": "string"},
						"subclassName": {"type": "string"},
						"subclassSource": {"type": "string"},
						"subSubclassName": {"type": "string"},
						"subSubclassSource": {"type": "string"}
					},
					"required": [
						"className", "classSource"
					],
					"additionalProperties": false
				},
				{
					"type": "string"
				}
			]
		}
	},

	"properties": {
		"_meta": {
			"$ref": "util.json#/definitions/metaBlock"
		},

		"class": {
			"type": "array",
			"items": {"$ref": "#/definitions/class"}
		},

		"subclass": {
			"type": "array",
			"items": {"$ref": "#/definitions/subclass"}
		},

		"classFeature": {
			"type": "array",
			"items": {"$ref": "#/definitions/classFeature"}
		},

		"subclassFeature": {
			"type": "array",
			"items": {"$ref": "#/definitions/subclassFeature"}
		}
	},
	"additionalProperties": false
}

=== daniel-giralt-len/5ein.es/data/class/class-sorcerer.json
{
	"_meta": {
		"dependencies": {
			"subclass": [
				"genèric"
			]
		}
	},
	"class": [
		{
			"name": "Bruixot",
			"source": "PHB",
			"page": 99,
			"srd": true,
			"hd": {
				"number": 1,
				"faces": 6
			},
			"proficiency": [
				"con",
				"xa"
			],
			"spellcastingAbility": "xa",
			"casterProgression": "ple",
			"cantripProgression": [
				4,
				4,
				4,
				5,
				5,
				5,
				5,
				5,
				5,
				6,
				6,
				6,
				6,
				6,
				6,
				6,
				6,
				6,
				6,
				6
			],
			"spellsKnownProgression": [
				2,
				3,
				4,
				5,
				6,
				7,
				8,
				9,
				10,
				11,
				12,
				12,
				13,
				13,
				14,
				14,
				15,
				15,
				15,
				15
			],
			"startingProficiencies": {
				"weapons": [
					"{@item daga|phb|dagues}",
					"{@item dard|phb|dards}",
					"{@item sling|phb|eslings}",
					"{@item quarterstaff|phb|quartersstaffs}",
					"{@item ballesta lleugera|phb|ballestes lleugeres}"
				],
				"skills": [
					{
						"choose": {
							"from": [
								"arcanes",
								"engany",
								"perspicàcia",
								"intimidació",
								"persuasió",
								"religió"
							],
							"count": 2
						}
					}
				]
			},
			"startingEquipment": {
				"additionalFromBackground": true,
				"default": [
					"(a) una {@item ballesta lleugera|phb} i {@item crossbow bolts (20)|phb|20 bolts} o bé (b) any {@filter simple weapon|items|source=phb|category=basic|type =arma simple}",
					"(a) una {@item component pouch|phb} o bé (b) an {@item arcane focus|phb}",
					"(a) una {@item dungeoneer's pack|phb} o bé (b) an {@item explorer's pack|phb}",
					"Dues {@item daga|phb|dagues}"
				],
				"goldAlternative": "{@dices 3d4 × 10|3d4 × 10|Or inicial}",
				"defaultData": [
					{
						"a": [
							"ballesta lleugera|phb",
							"parabolts de ballesta (20)|phb"
						],
						"b": [
							{
								"equipmentType": "armaSimple"
							}
						]
					},
					{
						"a": [
							"bossa de components|phb"
						],
						"b": [
							"focus arcà|phb"
						]
					},
					{
						"a": [
							"paquet de masmorres|phb"
						],
						"b": [
							"paquet de l'explorador|phb"
						]
					},
					{
						"_": [
							{
								"item": "daga|phb",
								"quantity": 2
							}
						]
					}
				]
			},
			"multiclassing": {
				"requirements": {
					"cha": 13
				}
			},
			"classTableGroups": [
				{
					"colLabels": [
						"Punts de bruixeria"
					],
					"rows": [
						[
							0
						],
						[
							2
						],
						[
							3
						],
						[
							4
						],
						[
							5
						],
						[
							6
						],
						[
							7
						],
						[
							8
						],
						[
							9
						],
						[
							10
						],
						[
							11
						],
						[
							12
						],
						[
							13
						],
						[
							14
						],
						[
							15
						],
						[
							16
						],
						[
							17
						],
						[
							18
						],
						[
							19
						],
						[
							20
						]
					]
				},
				{
					"colLabels": [
						"{@filter Cantrips coneguts|encanteris|nivell=0|classe=Sorcerer}",
						"{@filter Encanteris coneguts|encanteris|classe=Sorcerer}"
					],
					"rows": [
						[
							4,
							2
						],
						[
							4,
							3
						],
						[
							4,
							4
						],
						[
							5,
							5
						],
						[
							5,
							6
						],
						[
							5,
							7
						],
						[
							5,
							8
						],
						[
							5,
							9
						],
						[
							5,
							10
						],
						[
							6,
							11
						],
						[
							6,
							12
						],
						[
							6,
							12
						],
						[
							6,
							13
						],
						[
							6,
							13
						],
						[
							6,
							14
						],
						[
							6,
							14
						],
						[
							6,
							15
						],
						[
							6,
							15
						],
						[
							6,
							15
						],
						[
							6,
							15
						]
					]
				},
				{
					"title": "Nivells de Ranura per Nivells de Conjur",
					"colLabels": [
						"{@filter Nv.1|encanteris|nivell=1|classe=Sorcerer}",
						"{@filter Nv.2|encanteris|nivell=2|classe=Sorcerer}",
						"{@filter Nv.3|encanteris|nivell=3|classe=Sorcerer}",
						"{@filter Nv.4|encanteris|nivell=4|classe=Sorcerer}",
						"{@filter Nv.5|encanteris|nivell=5|classe=Sorcerer}",
						"{@filter Nv.6|encanteris|nivell=6|classe=Sorcerer}",
						"{@filter Nv.7|encanteris|nivell=7|classe=Sorcerer}",
						"{@filter Nv.8|encanteris|nivell=8|classe=Sorcerer}",
						"{@filter Nv.9|encanteris|nivell=9|classe=Sorcerer}"
					],
					"rows": [
						[
							2,
							0,
							0,
							0,
							0,
							0,
							0,
							0,
							0
						],
						[
							3,
							0,
							0,
							0,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							2,
							0,
							0,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							0,
							0,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							2,
							0,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							0,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							1,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							2,
							0,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							1,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							0,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							0,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							1,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							1,
							0,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							1,
							1,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							1,
							1,
							0
						],
						[
							4,
							3,
							3,
							3,
							2,
							1,
							1,
							1,
							1
						],
						[
							4,
							3,
							3,
							3,
							3,
							1,
							1,
							1,
							1
						],
						[
							4,
							3,
							3,
							3,
							3,
							2,
							1,
							1,
							1
						],
						[
							4,
							3,
							3,
							3,
							3,
							2,
							2,
							1,
							1
						]
					]
				}
			],
			"classFeatures": [
				"Llançament de Conjurs|Sorcerer||1",
				{
					"classFeature": "Origen bruixot|Feixot||1",
					"gainSubclassFeature": true
				},
				"Versatilitat de l'encanteri|Sorcerer||1|UAClassFeatureVariants",
				"Font de la Màgia|Sorcerer||2",
				"Opcions de font de màgia|Sorcerer||2|UAClassFeatureVariants",
				"Metamàgia | Bruixot||3",
				"Opcions de metamàgia|Sorcerer||3|UAClassFeatureVariants",
				"Opcions metamàgiques|Sorcerer||3|TCE",
				"Millora de Puntuació de Característica|Sorcerer||4",
				"Competència Versàtil|Sorcerer||4|UAClassFeatureVariants",
				"Versatilitat bruixot|Bàixor||4|TCE",
				"Guia Màgica|Bruixot||5|TCE",
				{
					"classFeature": "Característica Sorcerous Origin|Sorcerer||6",
					"gainSubclassFeature": true
				},
				"Millora de Puntuació de Característica|Sorcerer||8",
				"Competència Versàtil|Sorcerer||8|UAClassFeatureVariants",
				"Metamàgia|Foixor||10",
				"Millora de Puntuació de Característica|Sorcerer||12",
				"Competència Versàtil|Sorcerer||12|UAClassFeatureVariants",
				{
					"classFeature": "Característica Sorcerous Origin|Sorcerer||14",
					"gainSubclassFeature": true
				},
				"Millora de Puntuació de Característica|Sorcerer||16",
				"Competència Versàtil|Sorcerer||16|UAClassFeatureVariants",
				"Metamàgia|Foixor||17",
				{
					"classFeature": "Característica de l'Origen Bruixot|Foixor||18",
					"gainSubclassFeature": true
				},
				"Millora de Puntuació de Característica|Sorcerer||19",
				"Competència Versàtil|Sorcerer||19|UAClassFeatureVariants",
				"Restauració de bruixots|Hechicero||20"
			],
			"subclassTitle": "Origen bruixot",
			"fluff": [
				{
					"name": "Bruixot",
					"type": "secció",
					"entries": [
						"Uns ulls daurats brillants, una humana estira la mà i desferma el foc del drac que li crema a les venes. Mentre un infern s'ensorra al voltant dels seus enemics, unes ales de cuir s'estenen des de l'esquena i s'enlaira.",
						"Els cabells llargs assotats per un vent conjurat, un mig elf allarga els braços i tira el cap enrere. Aixecant-lo momentàniament del terra, una onada de màgia s'eleva en ell, a través d'ell, i surt d'ell en un poderós llamp.",
						"Ajupit darrere d'una estalagmita, un halfling assenyala amb el dit un troglodita carregant. Una explosió de foc brolla del seu dit per colpejar la criatura. Ella es torna darrere de la formació rocosa amb un somriure, sense saber que la seva màgia salvatge ha tornat la seva pell d'un blau brillant.",
						"Els bruixots porten un dret de naixement màgic que els atorga una línia de sang exòtica, alguna influència d'un altre món o l'exposició a forces còsmiques desconegudes. No es pot estudiar bruixeria com s'aprèn una llengua, com tampoc no es pot aprendre a viure una vida llegendària. Ningú tria la bruixeria; el poder tria el bruixot.",
						{
							"type": "entrades",
							"name": "Màgia crua",
							"entries": [
								"La màgia és una part de cada bruixot, que impregna el cos, la ment i l'esperit amb un poder latent que espera ser aprofitat. Alguns bruixots fan servir la màgia que neix d'una línia de sang antiga impregnada de la màgia dels dracs. Altres porten dins d'ells una màgia crua i incontrolada, una tempesta caòtica que es manifesta de maneres inesperades.",
